name: Daily Screenshot

on:
  schedule:
    - cron: "0 10 * * *"  # اجرای خودکار هر روز ساعت 10:00 UTC
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # Install Playwright dependencies
      - name: Install dependencies
        run: pip install playwright && playwright install

      # Run screenshot script
      - name: Run screenshot script
        run: python screenshot.py  # این باید به فایل screenshot.py اشاره کنه

      # Set up Git user for commit
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Commit and push the screenshot
      - name: Commit and push screenshot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # استفاده از توکن دسترسی برای انجام push
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add screenshots/
          git commit -m "New screenshot"
          git push https://$GH_TOKEN@github.com/${{ github.repository }} HEAD:main
